[build]
  command = "remix build"
  functions = "netlify/functions"
  publish = "public"

[functions]
  included_files = ["public/assets/**"]
  external_node_modules = ["@remix-run/react"]
[dev]
  command = "remix watch"
  port = 3000

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200

[[headers]]
  for = "/build/*"
  [headers.values]
    "Cache-Control" = "public, max-age=31536000, s-maxage=31536000"
